version: '3'

services:
  frontend:
    build:
      context: .
    ports:
      - "3000:3000"         
    volumes:
      - .:/usr/src/app 
    depends_on:
      - backend  

  backend:
    build:
      context: ./backend  
    ports:
      - "5000:5000"       
    volumes:
      - ./backend:/usr/src/app 
      - /usr/src/app/node_modules 
    environment:
      - REDIS_URL=redis://localhost:6379
      - MONGO_URI=mongodb://mongo:27017/BloodBankWebsite
    depends_on:
      - mongo  
      - redis  

  mongo:
    image: mongo
    ports:
      - "27017:27017"  
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    ports:
      - "6379:6379"   

volumes:
  mongo_data: